### PR TITLE
Mixtape model

### PR DESCRIPTION
**Pull request by treem0**
Lets take a look at this as a group to make sure this looks right.

### CODE REVIEW

**Comment by treem0** [comment]
need to fix

**Review by ianandrewson — COMMENTED** [review]
Mixtape Model: Song subschema looks super solid. I'm going to update the front end so that added songs have the thumbnail, buylink, and isMemo fields. 
On the actual mixtape model though, I think the songs array needs to be required. Also, since it won't be too hard to change these models later, I dont know if we should add a field for tags or not yet. It can't hurt, particularly if we're not going to require them. Since you're going to be in the file anyway, maybe add it now?

Lastly, did you mean to leave the virtual field for mixtapes on user commented out?

**Comment by ianandrewson** [comment]
Also, on the song subschema for Mixtape, can we change the Id field to nativeId, source to nativeSource, and thumbnail to thumbnailUrl?

**Review by ianandrewson — APPROVED** [review]
Looks super solid!

**Pull request merged**
